### ISSUE TITLE
Files with wrong CSS class.

### ISSUE THREAD

**Issue by rodrigo-rufino** [vrtmrz/obsidian-tagfolder#10]
The files on the TagFolder pane have the wrong css class.

Current class: `nav-folder`
Correct class: `nav-file`.

![Captura de Tela 2022-01-25 às 17 06 57](https://user-images.githubusercontent.com/18670446/151051345-fc29e46a-1dac-47c1-8a14-e1e102179334.png)
![Captura de Tela 2022-01-25 às 17 07 23](https://user-images.githubusercontent.com/18670446/151051414-8561d7a5-e0d2-41cb-8ff6-3b245910a48b.png)

**Comment by vrtmrz** [comment]
@rodrigo-rufino 
Sorry for the delay!
I didn't use themes that have different appearances of files and folders, I didn't catch it.
This problem has been fixed. 
Could you please try v0.9.0?
