### ISSUE TITLE
Unexpected plugin behavior: wrong tree, root tag in trird level

### ISSUE THREAD

**Issue by DimaRU** [vrtmrz/obsidian-tagfolder#100]
BUG: Unexpected plugin behavior: wrong tree, root tag in trird level.
First screenshot - TagFolder pane (List files in separated pane on)
Second screenshot - tags pane expanded.

<img width="357" alt="Screenshot 2024-03-24 at 14 12 20" src="https://github.com/vrtmrz/obsidian-tagfolder/assets/2822604/fd3ab9e3-a80d-49ff-abde-ea71849ef6fd">
<img width="423" alt="Screenshot 2024-03-24 at 14 13 17" src="https://github.com/vrtmrz/obsidian-tagfolder/assets/2822604/8272d9c6-604f-4d09-8970-e20cb1ed78cc">

**Comment by vrtmrz** [comment]
Thank you for reporting it to me! And sorry for being late!
It has been reproduced! 

I will address it later!

**Comment by vrtmrz** [comment]
@DimaRU 
Fortunately, it could be fixed pretty quickly.
Would you mind if I ask you to check v0.18.7, please?
