### ISSUE TITLE
List files in separated pane not working after update

### ISSUE THREAD

**Issue by mjknght** [vrtmrz/obsidian-tagfolder#108]
Hi there,

My way of using TagFolder is to list files in a separated pane at the bottom of the left sidebar, with the tag tree in the top part. But after the update, “List files in separated pane” appears to have stopped working. Whether Show List it is set to “Sidebar” or to “New pane”, the separated pane just shows the tag list a second time – it never shows the list of files.

Thanks in advance for looking into this!

**Comment by vrtmrz** [comment]
Thank you for reporting this! I have completely missed this!
I will address it soon!

**Comment by vrtmrz** [comment]
At 0.18.9, It should be fixed! Would you mind if I ask you to check the behaviour, please?

**Comment by mjknght** [comment]
Updated, and this works a treat. Thank you!

**Comment by vrtmrz** [comment]
I am very happy to hear that! I close this issue with thanks!
