### ISSUE TITLE
File and folder icon

### ISSUE THREAD

**Issue by HuangAdam** [vrtmrz/obsidian-tagfolder#12]
Too difficult to identify folder and file

**Comment by vrtmrz** [comment]
@HuangAdam 
TagFolder uses the same class as obsidian's File Explorer.
Actually, It has been corrupted but fixed in v0.9.0.
Could you please try v0.9.0 and some themes?

**Comment by HuangAdam** [comment]
@vrtmrz 
Thanks!
It has been fixed successfully.
