### ISSUE TITLE
Ignore notes in specified folders

### ISSUE THREAD

**Issue by PaulHerrero** [vrtmrz/obsidian-tagfolder#13]
Hopefully the notes in the specified folder can be ignored. Thank you

**Comment by aubreyz** [comment]
+1 - I agree this would be useful - for example to ignore template folders. It would also be useful to maintain a standard list of tags for autocompletion (in a hidden folder) where these tags do not disappear from autocompletion when the last tag is deleted (or to transfer a standard tag list from one vault to another without causing clutter).

**Comment by vrtmrz** [comment]
Thank you for making the issue and giving me use-cases.
I think it is very useful too.
So I implemented this. 
Could you please try v0.9.0?

**Comment by PaulHerrero** [comment]
> Thank you for making the issue and giving me use-cases. I think it is very useful too. So I implemented this. Could you please try v0.9.0?

Thankfully, it meets my needs very well

**Comment by aubreyz** [comment]
It works great
