### ISSUE TITLE
FR: Notes sorting options?

### ISSUE THREAD

**Issue by VKondakoff** [vrtmrz/obsidian-tagfolder#2]
Hello!

Thanks for such an useful plugin! Testing it right now.
Looks like currently there are no notes sorting options and the notes are sorted in reverse alphabetical order with some not obvious exclusions...

Here is a screenshot:
<img width="338" alt="Снимок экрана 2021-12-14 в 01 01 54" src="https://user-images.githubusercontent.com/230824/145896258-3ceac4b2-5fd5-4215-ae3e-a61de6e47a9d.png">

**Comment by vrtmrz** [comment]
Thank you for trying this plugin! 
I didn't notice that sorting was broken.

I've fixed this and implemented the feature that customizes file ordering.
I didn't check in other languages, but if Obsidian respects the platform's locale, "Peremeshcheniye po stroke" would be also sorted correctly.

**Comment by vrtmrz** [comment]
@VKondakoff 
Sorry, I forgot the mention. Does version 0.4.0 works for your device well?

**Comment by VKondakoff** [comment]
> I've fixed this and implemented the feature that customizes file ordering.

Thanks! Works just great:

<img width="344" alt="Снимок экрана 2021-12-16 в 11 14 12" src="https://user-images.githubusercontent.com/230824/146333386-b04a1bc0-1629-462a-8755-91923bc84324.png">

> Does version 0.4.0 works for your device well?

I just have installed Tagfolder 0.4.0 on macOS, iOS and iPadOS. At first glance everything works as expected. Will report later tomorrow if there are any issues.

Thanks for Tagfolder: personally, this is one of the most important plugins for my workflow!
