### ISSUE TITLE
FR: Support for context menus

### ISSUE THREAD

**Issue by isle9** [vrtmrz/obsidian-tagfolder#21]
Currently, the only option we get when we right click an item is to copy the tags, but it would be nice if the native context menu was supported.

**Comment by vrtmrz** [comment]
Thank you for your request!
I thought so too. And now, this feature has been being corrupted.
I will fix this and enhance it.

**Comment by vrtmrz** [comment]
@isle9 
This has been implemented in v0.11.0. Could you please try this version?

**Comment by isle9** [comment]
Yap, works!
