### ISSUE TITLE
FR: Show only nested Tags

### ISSUE THREAD

**Issue by emillienemann** [vrtmrz/obsidian-tagfolder#26]
I think a way to show only nested Tags in a folder structure and not show anything else would be really useful.

**Example File rice dish.md**
`#cooking/rice #health/fitness`

**Current result (Intermediates of nested tags hidden)**
```
cooking
   -> rice
      rice dish
      health
         -> fitness
             rice dish
health
    -> fitness
       rice dish
       cooking
          -> rice
            rice dish
```

**Described Result**
```
cooking
   -> rice
      rice dish
health
   -> fitness
      rice dish
```

**Comment by ryanfys** [comment]
I'd like this way to show the result. Hope to come true.

**Comment by ThatNerdSquared** [comment]
+1, this would be great - open to contributing if needed, if a maintainer provides their thoughts.

**Comment by vrtmrz** [comment]
Thank you all for your idea and suggestions!
Implementation is possible, but the code base is currently a bit flaky.

@ThatNerdSquared 
Of course I will welcome your contribution!

**Comment by ThatNerdSquared** [comment]
@emillienemann unfortunately I won't be able to tackle this in the near future, due to other obligations. I will poke around the codebase and see if I can start on an implementation or write up possible approaches, but I likely won't be able to create any PRs for another month or so.

**Comment by emillienemann** [comment]
@vrtmrz 
Putting a bounty of 20 USD one time via GitHub sponsors on this, if it‘s implemented in the next 30 days in case you‘re interested

**Comment by vrtmrz** [comment]
Sorry for being late in replying!
I am a bit worried about the bounty because I cannot always respond to them. But I will try to work on this feature. I felt that it means that it is such a desired feature.

However, may I ask a bit more?

If there are also bare tags, like: `#cooking/rice #health/fitness #draft`, `#draft` should be ignored?  Or, `#draft` folder is created at the root but not displayed under `#cooking/rice`?
Does it means "Do not structure unrelated multiple tags"?

**Comment by emillienemann** [comment]
@vrtmrz 
No worries if you can’t get to doing this, I understand the bounty amount is more symbolic rather than being a real developer salary.
In the case described, bare tags would be shown at root, but not in any folders. 

## Example Files
### File1.txt
`#bareTag #bigTag/subtag #otherBareTag`
### File2.txt
`#bareTag #bigTag`

## Example Output
```
bareTag
  File1
  File2
otherBareTag
  File1
bigTag
  subtag
    File1
  File2
```

**Comment by vrtmrz** [comment]
Thank you for the detail! And, thank you for your kindness! I also think that is symbolic.

It has been implemented as “Disable narrowing down”! It looks handy than I thought.
May I ask you to check the behaviour?

**Comment by emillienemann** [comment]
> Thank you for the detail! And, thank you for your kindness! I also think that is symbolic.
> 
> It has been implemented as “Disable narrowing down”! It looks handy than I thought. May I ask you to check the behaviour?

Works amazingly! I have sponsored you 20 USD. Thanks for the amazing Open Source work!

**Comment by vrtmrz** [comment]
I am very glad to hear that. And very much appreciate your support! 
Your noble kindness would make our plugins even better. Thank you very much again!
