### ISSUE TITLE
[Another FR] option in context menu to pin tags

### ISSUE THREAD

**Issue by afland** [vrtmrz/obsidian-tagfolder#28]
Should optimally work to pin parent tags + their entire nested structure and also allow for pinning individual/nested tags

With folder organization, it's easy to prefix a folder with ex. 00 Index Notes, 01 School, etc. 
With tags, that's obviously a little less convenient

It would be helpful if the pinned tags were organized in the order they were pinned rather than alphabetically for a completely custom order. Being able to drag them around to re-order would also be a plus.

Thanks for the great development on this plugin! Hopefully I'll have the funds to sponsor one day :pray:

**Comment by vrtmrz** [comment]
It is an amazing proposal! I realised that we needed this.
Implemented on v0.13.0. Would you please check the behaviour?

When I rearranged by drag-drop, I lost the rule and got lost again inside the pinned items. So they can be ordered according to the key in the information file. 
The information file is markdown. We can merge changes between vaults.
