### ISSUE TITLE
[FR] expand all nested tags if there are no notes in the intermediate tags

### ISSUE THREAD

**Issue by afland** [vrtmrz/obsidian-tagfolder#33]
Say you only have 1 note in your vault with `#topic/dev/java`

Expanding all of those individually is unnecessary because you only see a note once you get to the `java` nested tag anyway. 

So when you click expand on any tag (parent or any level nested tag), all nested tags below that should be expanded until a note is encountered.

**Comment by vrtmrz** [comment]
I thought this behaviour is as like as Java repo of GitHub, and implemented so on v0.14.1. 
Could you please check the behaviour?

Note:
If three normal tags are nested, they will not be merged into one tag. 
(To find a note out, I think we will choose the tag in order of just remembered)
If you want to merge them, please enable `Merge redundant combinations` on the setting dialog.
