### ISSUE TITLE
Tags are not case sensitive any more

### ISSUE THREAD

**Issue by joellti** [vrtmrz/obsidian-tagfolder#34]
Starting with version 0.12.0 all my tags are showing low case now even though some of them containing upper case characters. I also notice that the native tag pane shows the tags with correct cases. Hope the feature can be restored. Thx

**Comment by vrtmrz** [comment]
@joellti 
Thank you for notifying me! I felt something wrong while fixing some logic, and I became convinced to see this issue.
Fixed on v0.14.3, could you please check this?

**Comment by joellti** [comment]
Yes I can confirm it's working again. Thanks a lot @vrtmrz
