### ISSUE TITLE
Are multiple nested tags in conflict with each other?

### ISSUE THREAD

**Issue by Concibar** [vrtmrz/obsidian-tagfolder#36]
This Plugin is AWESOME thank you so much for making it! :)

I just spend 2 hours tagging all my notes, now that I can use tags exactly how I want to, however I encountered a small issue.

It might very well be that I fucked up with my syntax although I double checked everything:

I have a note that is tagged with #Bloodmerchants #Bloodmerchants/Setting and #ttrpg/Mechanics
TagFolder Gives me the note in the Folder at only 3 not places however:
- Bloodmerchants/Setting/ttrpg/Mechanics
- Bloodmerchants/Setting
- Bloodmerchants
(It also shows up under ttrpg/Mechanics/Bloodmerchants, and under ttrpg)

Why doesn't it display the note under
- Bloodmerchants/ttrpg/Mechanics
?
I have three other Notes that are tagged with #Bloodmerchants and #ttrpg/Mechanics  so I suspect the #Bloodmerchants/Settings tag has something to do with it, I just don't understand why.

I'm on windows. I turned of all the option to "Merge redundant combinations" and switched from "Hide Only Intermediates" to "Hide nothing" and restarted Obsidian to no avail.
![image](https://user-images.githubusercontent.com/111504225/185381192-ecdfea4a-ce0a-4e51-98f3-c765929b2b13.png)

**Comment by vrtmrz** [comment]
Thank you for asking me!
This was my naive idea while developing, and actually, I missed the cases as you pointed out.
https://github.com/vrtmrz/obsidian-tagfolder/blob/eb9abf002fa3745c6cbf8817497c4a51a529725c/main.ts#L1121-L1125

I fixed this at v0.14.5, could you please check the behaviour?

**Comment by Concibar** [comment]
Thanks for the quick fix!
I just updated and checked and yes: The whole thing is now working as intended :)
I am so glad I found this mod, I am used to "tagging for windows" for all my files and found obsidians tagging to be lacking before I found TagFolder.
I am starting to learn programming maybe I can appreciate what you fixed more fully once I understand did ;)
I'll return I notice anything not working as intended but so far I'm just very happy with this plugin, thank you for making it once more :)
