### ISSUE TITLE
Include specific folders only

### ISSUE THREAD

**Issue by joellti** [vrtmrz/obsidian-tagfolder#37]
Thanks a lot for developing this great plugin. I use this plugin a lot since it fits my work flow perfectly. Currently I'm using its Ignore Folders feature to reduce the scope and it works well most of time. But often time I had to add extensive list of ignored folders just to be able to narrow down the scope to include only a couple of folders. I think it will be much easier if the user only needs to specify the folders to include rather than to ignore. Hope you would consider adding this option. It will definitely make me and other users life a lot easier.

**Comment by vrtmrz** [comment]
I'm very honoured, thank you for your praise!
I think your idea is useful and easy to implement.
It will be implemented.

**Comment by vrtmrz** [comment]
@joellti Sorry for being late! 
This feature has been implemented at v0.15.2.
Could you please test it?

**Comment by joellti** [comment]
My brief test confirms that it's working as expected. Thanks again for your speedy turnaround delivering this key feature.
