### ISSUE TITLE
[FR] Right click tag to create new note with the tag already set

### ISSUE THREAD

**Issue by marcesquerra** [vrtmrz/obsidian-tagfolder#39]
To leave behind the folder view and live in "TagFolder" view instead, it would be really nice to be able to create a new note "inside" a particular tag.

What I'm thinking of is to be able to right-click a tag in "TagFolder" and have a command in there named "New Note". And when you click that command, a new note gets created in the default path, but with the body of the note initialized to contain the tag.

For example, in this image:
![newNoteFromTag](https://user-images.githubusercontent.com/2683206/187091986-4ff00f38-0a3c-484e-89b3-6c84150cebcc.png)

there would be a second command named "new" or "new note", and when clicked, the new note would have `#project/goSEM` as it's only content.

Would that be something feasible?

**Comment by vrtmrz** [comment]
Thank you for your request! I think it will be useful.
What I am doing is clicking `Copy tags` and `Ctrl+N` and `Ctrl+V`. But now I think it is a roundabout way.

**Comment by marcesquerra** [comment]
I've tried the new note functionality you've added in the new version, and works like a charm!

Thanks, @vrtmrz !!!

**Comment by vrtmrz** [comment]
Sorry for missing announcement.
I’m very glad to hear that!
