### ISSUE TITLE
FR: add functional buttons to tagfolder pane

### ISSUE THREAD

**Issue by VKondakoff** [vrtmrz/obsidian-tagfolder#4]
Hi!

I think it will be great to see some some functions buttons right in the  tagfolder pane (like in file explorer):

<img width="369" alt="Снимок экрана 2021-12-16 в 22 04 15" src="https://user-images.githubusercontent.com/230824/146432805-44d33acf-90d9-493f-99ec-ca48a4ea431a.png">

Possible buttons: Create new note (like in file explorer), Sort Тags, Sort Notes,  Switch modes (if[ this FR](https://github.com/vrtmrz/obsidian-tagfolder/issues/3) will be implemented).

What do you think?

**Comment by vrtmrz** [comment]
It would be very useful! 
If you don't need to specify the folder that new note spawn, it will no so difficult.

**Comment by vrtmrz** [comment]
@VKondakoff 

Thank you for requesting! 
Implemented!

**Comment by VKondakoff** [comment]
Perfect, thanks!
