### ISSUE TITLE
FR: add 'Open in new tab' entry to note right-click menu

### ISSUE THREAD

**Issue by VKondakoff** [vrtmrz/obsidian-tagfolder#42]
Hi!

As there are tabs in the newest Obsidian builds it will be great to have 'Open in new tab' entry to note right-click menu.

<img width="295" alt="Снимок экрана 2022-10-06 в 14 19 25" src="https://user-images.githubusercontent.com/230824/194300113-494715a0-0caf-467f-b168-d4e0dd97c4c5.png">

Thanks!

**Comment by Concibar** [comment]
I second this, it would be very neat if the TagFolder list reacted to Shift/Strg + left-clicks by opening new tabs/windows accordingly :)

**Comment by vrtmrz** [comment]
Thank you for your idea! It will probably be useful. And, sorry for being away a bit long.
It will be implemented!

**Comment by Concibar** [comment]
@vrtmrz We are the ones who have to be thankful! I would still be looking for Obsidian-alternatives if not for the free work you provide via this Add-On! I really appreciate what you do here :)
