### ISSUE TITLE
Triangle icon in tags tree does not respect the expanded/collapsed state

### ISSUE THREAD

**Issue by VKondakoff** [vrtmrz/obsidian-tagfolder#48]
Triangle icon in tags tree does not respect the expanded/collapsed state:

<img width="345" alt="Снимок экрана 2022-10-14 в 00 30 24" src="https://user-images.githubusercontent.com/230824/195714565-bcb81136-5345-44c5-81c1-d2a3f865fffd.png">

I was expecting to see ▶ for collapsed group and ▼ for expanded group (at least this is how File explorer icons are working).

**Comment by vrtmrz** [comment]
Hi! Thank you for notifying me! Finally, I upgraded Obsidian and realised.

I used SVG images from the old Obsidian that was copied and pasted. If fixed like this, It should make the matter again. 

Fixed to use of the icon that is actually used in Obsidian. So now it will be affected if you are using icon-swapper.
Could you please try v0.15.6?

**Comment by VKondakoff** [comment]
Looks great, thanks for fixing!

<img width="341" alt="Снимок экрана 2022-10-19 в 13 04 39" src="https://user-images.githubusercontent.com/230824/196662001-bc800f92-037e-4573-94a7-a682aff39d36.png">

I'm closing the issue.
