### ISSUE TITLE
FR: filter

### ISSUE THREAD

**Issue by tombroens** [vrtmrz/obsidian-tagfolder#5]
Would it be hard to have a text based filter for the tag names? Hence to have kind of search in de hierarchy? Maybe an issue with the many possible levels (limit to the opened tags)?

**Comment by vrtmrz** [comment]
Thank you for requesting a new feature. I think it would be useful.
It doesn't so hard, I'll implement this.

**Comment by vrtmrz** [comment]
@tombroens 
I implemented this feature. Could you please check it?

**Comment by tombroens** [comment]
Wow you are great. This is also amazing but not completely what I was expecting ;-). Does it now do a tag search and then show all the tag 'folders' that contain notes with that tag? Probably add two things and it can do everything:
- a checkmark 'show all' that performs the current behaviour, and without check it filters towards the targeted specific tag in the list (e.g. when typing 'person' it shows the 'person' tag folder, or when typing 'JohnDoe' it shows the 'person' tag folder as it contains the JohDoe nested tag)
- an autocomplete for the tag name when typing in the search field (nice to have)
- it seems to already support some boolean operators? (could have)

**Comment by vrtmrz** [comment]
I am really sorry to late! 

So, if show all checkmark is checked,  Expand matched tag all automatically?
The simple operator is implemented( just and, or)
- and is simply connect the tags
- or is "|". It's stronger than and.

**Comment by V-U-Simon** [comment]
It will be difficult to implement ignore case sensitivity in searching? 
Maybe it will be toggle.

I think it more comfortable in searching at workflow.

**Comment by vrtmrz** [comment]
@V-U-Simon 
Sorry, it's a bug. Fixed on v0.8.1.
Tag name should be case insensitive (#6)
