### ISSUE TITLE
FR: please, make canvases visible to TagFolder

### ISSUE THREAD

**Issue by VKondakoff** [vrtmrz/obsidian-tagfolder#52]
Hi!

Obsidian v1.1 introduces canvases. Currently there is no way to add tags directly to canvas, so I think TagFolder should show canvases in `untagged` section by now.

**Comment by vrtmrz** [comment]
Thank you for your request! 
I think it should be too! However, my `_untagged` folder is almost like a junkyard.
I thought it could be better with marked inside there. (Getting weird about what `untagged` means, but I will not think about it till we get a good idea.)

It has been implemented at v0.15.11, could you please try this?

**Comment by VKondakoff** [comment]
Thanks for implementing this. Right now canvases are shown both in `_untagged` and `_canvas untagged` categories: 
<img width="338" alt="Снимок экрана 2022-12-26 в 12 24 32" src="https://user-images.githubusercontent.com/230824/209531446-3fc1b977-7e1c-4936-99f1-dc2febdc1fbd.png">

This is Ok for me, at least until Obsidian devs implement [proper metadata support for canvase-files](https://forum.obsidian.md/t/canvas-make-links-to-canvas-appear-in-backlinks-and-graph-view/49094). Let's think about right placement of untagged canvases when there will be proper tags support for canvase-files.

**Comment by vrtmrz** [comment]
Thank you for your checking! 

> Let's think about right placement of untagged canvases when there will be proper tags support for canvase-files.

I think so too. I close this issue once with your help!

**Comment by Flanpit** [comment]
I'm seeing that this is supposed to be a feature of tag folder, however I do not like seeing `#_untagged #📋 Canvas` at the top of my tag folder window. Is there no way to hide this?

<img width="1041" height="217" alt="Image" src="https://github.com/user-attachments/assets/8b770251-42a5-4186-bd5b-1dbe1add534f" />
