### ISSUE TITLE
Two pane view

### ISSUE THREAD

**Issue by RobinLandy** [vrtmrz/obsidian-tagfolder#55]
Would you consider adding an option for a 2-pane view? So the list of note titles appear _to the right_ of the list of tag titles, instead of underneath them? I've mocked-up a wireframe.

<img width="1345" alt="Screenshot 2023-01-03 at 12 28 57" src="https://user-images.githubusercontent.com/121885842/210396188-c242c2b5-3c91-4d77-8bba-142094044a07.png">

**Comment by liangzh-404** [comment]
> 

it's a pane that can be dragged. you can change its position

**Comment by vrtmrz** [comment]
Thank you for requesting the feature! and your wireframe made me so good to understand. (And sorry for all of you that previously requested the feature which was possibly the same.)

On 0.15.14, we can use this on the mobile too. As separated pane, or switching inside floating panes.
Could you please try v0.15.14? 

@liangzh-404 Thank you for noticing that! And a bit useful feature, we can pin the list if we have been interested in a specific combination of tags.

**Comment by RobinLandy** [comment]
@vrtmrz This is brilliant. Thank you so much for adding the second pane! It has instantly been a big improvement to Obsidian on desktop.

I've tried it also on mobile (iOS) and it works there too - albeit, I think the main usecase for second pane is on desktop.

**Comment by vrtmrz** [comment]
It cheers me up to hear you say that.
Thank you, too, for your request to make this plugin better. 

P.S. setting pane now makes a bit sense.
