### ISSUE TITLE
Weird multi-tag folder name

### ISSUE THREAD

**Issue by chnejohnson** [vrtmrz/obsidian-tagfolder#57]
Hello @vrtmrz,

I really like this project which provides a feature that allows managing tags like folders.

But there is a problem I don't understand. In the following example, I just have a file with two tags. I don't know why the folders tree shows up as two folders: `tag1 tag2` and `tag2 tag1`?

I think the folder name should be `tag1` and `tag2`, isn't it?

![截圖 2023-01-07 下午4 28 08](https://user-images.githubusercontent.com/31992185/211141388-58322ef3-dc3d-4d31-81fc-385ff8078377.png)

**Comment by vrtmrz** [comment]
Thank you for asking me! This is designed behaviour. 

TagFolder is able to organise notes but was initially designed to find notes. We will be able to reach the note, even though we remembered only tag1 or tag2.
However, Now we can suppress it by `Merge redundant combination` in general cases.

And, the folder which has no notes will be simplified. This behaviour is also can be disabled by `Do not simplify empty folders`.

I hope this is an answer to your question.

P.S. I have noticed that after writing this far, I feel that this is due to the fact that it is difficult to understand how these settings work. Maybe we need a previewer.

**Comment by chnejohnson** [comment]
@vrtmrz  Thanks! The option works for me 🙏

Yeah, actually I don't really understand `Do not simplify empty folders` so far. Maybe updating the description would be helpful.

I come to Obsidian from [Bear](https://bear.app/) and its folder system is nice to me.

And there are some small things I hope there is an option to toggle them. Do you have any idea about the following points that I would like to remove?

![截圖 2023-01-08 下午3 23 07](https://user-images.githubusercontent.com/31992185/211185120-c0dcc161-6c97-4acd-b016-c1e741fb2cb2.png)

**Comment by vrtmrz** [comment]
I am happy to hear that! 

I had no experience with Bear, but it must be a good solution that was designed so reasonably!

> And there are some small things I hope there is an option to toggle them. Do you have any idea about the following points that I would like to remove?

This might be available by setting Expand Limit to Level 1.
Could you please try? It can be set by this icon.

![30A7AC9E-E447-46AE-B33B-86AA946124C4](https://user-images.githubusercontent.com/45774780/211599408-9fd2fd18-08ca-474b-9068-6f4fb7d6bb7a.jpeg)

**Comment by chnejohnson** [comment]
Yeah, I think it does remove the subfolder, but it seems to duplicate some files 😅

![截圖 2023-01-11 下午3 57 11](https://user-images.githubusercontent.com/31992185/211749690-b7446e2a-ccba-4181-8238-ae015526a1e1.png)

**Comment by vrtmrz** [comment]
Oh, Thank you for pointing it out!
I did not has realised this but it looks like it had been so a bit while.

Fixed this at 0.15.16, I am sorry to make you troublesome but could you please check it again?

**Comment by chnejohnson** [comment]
No worries, thank you for your updates!

The 0.15.16 version works well without duplicated files 👍 
![截圖 2023-01-11 下午5 38 09](https://user-images.githubusercontent.com/31992185/211771630-a8cbc0f8-028b-424e-9173-e4cec1eaddce.png)

**Comment by chnejohnson** [comment]
There is a point that might be my personal preference (but it's also what works on Bear) that I would like to hide the file when it is using a sub tag without a normal one.

I mean in this case, `Test2` which is under folder `tag1` should be hidden.

![截圖 2023-01-11 下午5 46 07](https://user-images.githubusercontent.com/31992185/211773047-0a12945e-9c7d-438b-8dce-e2226a713116.png)

But in the following case, `Test2` should show up both under folder `tag1` and `tag1-1`

![截圖 2023-01-11 下午5 47 39](https://user-images.githubusercontent.com/31992185/211773256-c8e9f313-ddfb-4886-94de-f8cdff7e7813.png)

**Comment by vrtmrz** [comment]
I am very happy to hear that!
Thank you for your cooperation in debugging and making things better!

**Comment by chnejohnson** [comment]
@vrtmrz Hey, would you happen to have a public ETH address in your project readme or somewhere that I can make a crypto donation to support your development efforts?

**Comment by vrtmrz** [comment]
I am very honourable to hear about your kindness! I was not familiar with it before, but now I am interested in it. Also technologically.
I will see how to create my own address.

**Comment by chnejohnson** [comment]
Great! Have fun exploring ☕️
