### ISSUE TITLE
FR: Archive functionality / tag to help decrease clutter 

### ISSUE THREAD

**Issue by Chris-Fourie** [vrtmrz/obsidian-tagfolder#58]
Hi there (",) 

Thank you so much for this add-on! I feel all systems should have this approach as a default built-in option for organising files! 

It would be great to be able to archive documents to decrease clutter. 

I imagine functionality, that when enabled, allows for one or more tags to be specified that when added to a document, all files with one of these tags will be bundled at the top/root level under that tag. 

Effectively this may look like any document that has a user-specified "archive" tag, will have all tags associated with it become a nested tag with "archive" as the top-level tag.

E.g. If the user-specified tag is simply "archive"... then all tags associated with that document become "archive/tag1, archive/tag2/tag3, archive/tag4" etc. so that when rendered in the side panel, they are placed under a top-level "archive" tag.

This would decrease clutter at a top/root level and effectively add archive functionality.

**Comment by vrtmrz** [comment]
Thank you for your request! 
I realised that this is so an brilliant feature immediately and implemented it. And it looks like works as we thought. 

Could you please check v 0.15.15?

**Comment by s-walrus** [comment]
Hi!

Thanks for implementing the archive feature, I was looking for this exact functionality and was glad to find it in a plugin I already use. But I've encountered an issue: if "Disable narrowing down" is turned on, notes with an archive-tag are displayed in the menu not only under the archive tag, but also under the other tags included in the note. Basically, archive-tags doesn't make any difference if "Disable narrowing down" is on.

How to reproduce:
1. (optionally) create a new vault, install the tagfolder plugin
2. Add "archive" to the "Archive tags" option
3. Create a few notes: one with tags `#work #archive`, others just with the `#work` tag
    * *Now the feature works perfectly fine (as shown at the first screenshot)*
4. Turn on "Disable narrowing down" option in the plugin settings
    * *The feature is broken: file1 is displayed both under the `archive` tag and under `work` tag :( (second screenshot)*
<img width="511" alt="Screenshot 2023-06-15 at 12 47 03" src="https://github.com/vrtmrz/obsidian-tagfolder/assets/25895611/d783f20e-3350-46ac-88cd-fe7f308d4717">
<img width="511" alt="Screenshot 2023-06-15 at 12 49 17" src="https://github.com/vrtmrz/obsidian-tagfolder/assets/25895611/4e17dcec-d9cc-4564-ade8-9d60c03bd08d">

**Comment by vrtmrz** [comment]
Sorry for being late to inform you!
As you pointed out, it had been completely meaningless while `Disable narrowing down` was enabled.

It has been fixed at v0.15.25. Could you please check the behaviour?

**Comment by s-walrus** [comment]
> It has been fixed at v0.15.25. Could you please check the behaviour?

Now if multiple achive-tags are specified, notes with any one of them are displayed under all archive-tags :] It doesn't seem like intended behavior to me, is it?

See the screenshot: I set archive tags to `trash,archive,aboba` and `file1` is displayed under all three tags istead of only `trash`

<img width="504" alt="Screenshot 2023-06-21 at 14 32 25" src="https://github.com/vrtmrz/obsidian-tagfolder/assets/25895611/88669273-f72b-43d7-b7f7-540b9e37a7a3">

**Comment by vrtmrz** [comment]
Oh, what a careless mistake. I so regret letting you down.
It has been fixed at 0.15.26.  I am afraid to ask it twice, but could you try again?

**Comment by s-walrus** [comment]
The plugin works perfectly fine for me now. Thank you for fixing the issue! I appreciate that you find time to maintain the plugin
