### ISSUE TITLE
Tags case sensitive

### ISSUE THREAD

**Issue by adamshand** [vrtmrz/obsidian-tagfolder#6]
Hello,

I just found your plugin and it's great, thank you!

I notice that tags in tagfolder seem to be case sensitive where they are case insensitive in the rest of Obsidian.

I had both tags `#adam` and `#Adam` in my notes.  In the main Obsidian tag view I only see `#adam`, but in tagfolder I see `#Adam` and `#adam`.

To my mind it would be nice if the behaviour of tagfolder was consistent with the rest of Obsidian.

Many thanks for the lovely plugin.
Adam.

**Comment by vrtmrz** [comment]
Thank you for using the plugin!
Reproduced.

It will be fixed in the next release.

**Comment by adamshand** [comment]
Thank you!
