### ISSUE TITLE
Better visual separation of tags

### ISSUE THREAD

**Issue by ggstrader** [vrtmrz/obsidian-tagfolder#60]
It's very difficult to tell in this example that there are actually 2 different tags.
![image](https://user-images.githubusercontent.com/101308963/213637945-bf36ba4c-489a-4f9f-8558-011173796bef.png)

The view would be more readable if the pill-style tags with slashes were used rather than plain text with arrows
![image](https://user-images.githubusercontent.com/101308963/213638407-0bb59f80-d922-49bf-93de-61565d0a46ef.png)

At the very least, switching to slashes and putting more space between would help.
i.e. `organization/lists/packing  health/physical/climbing`

**Comment by vrtmrz** [comment]
Thank you for suggesting it! possibly depends on the personal flavour, but I am also wanted to customise easily. 

We can customise this from v0.15.17 by applying styles, by css snippets. 

I am sorry that I could not type so much on my mobile phone. But these classes can be useful for this issue. 

```
.tagfolder-tag.tag-tag {
/*here for the pill style*/
}
.tagfolder-tag.tag-nested-tag::before {
	content: "→ "; /* the delimiter of nested tags */
}
``` 

Could you please try this version?
Sorry for the rough reply!

**Comment by ggstrader** [comment]
> .tagfolder-tag.tag-tag {
> /*here for the pill style*/
> }
> .tagfolder-tag.tag-nested-tag::before {
> 	content: "→ "; /* the delimiter of nested tags */
> }

That doesn't work for the arrows, it looks like they are embedded in the text:
![image](https://user-images.githubusercontent.com/101308963/215172670-740e85b6-1fc4-4a35-a462-a599bc2d3fe1.png)

**Comment by ggstrader** [comment]
@vrtmrz after updating, it looks like that's working. Thanks!
