### ISSUE TITLE
data in TagFolder is not updated if space is used

### ISSUE THREAD

**Issue by accept82** [vrtmrz/obsidian-tagfolder#63]
Good afternoon Thank you for such a useful tool - it really is a huge contribution to the development of Obsidian!

Error:
I found that if I create a space configured to work with the TagFolder plugin (let's call the space Tags)
then I go to the main workspace (let's call it Main) and create new tags in the main workspace, then when I switch to the workspace Tags - the tags that I created in the main space are not displayed.
maybe something is not updated. Please check this information!

**Comment by vrtmrz** [comment]
Sorry for missing this issue! I have no experience to use the workspace and have not noticed.
However, I could not reproduce this yet. May I ask about your configuration?

**Comment by accept82** [comment]
Good afternoon, I checked it on a clean configuration - everything is updated and works well, perhaps - something was not updated for me. I post a video that everything works well. Thank you for your time.

https://user-images.githubusercontent.com/90281362/224998318-ba13195b-2549-4f0f-b3b8-f50f170fcfdd.mp4
