### ISSUE TITLE
color set not work with minimal theme

### ISSUE THREAD

**Issue by liangzh-404** [vrtmrz/obsidian-tagfolder#68]
the tag number and tag for specific notes are masked.
<img width="274" alt="image" src="https://user-images.githubusercontent.com/31941670/222943793-00a839f6-c394-426b-a37b-53f0102815d2.png">
<img width="282" alt="image" src="https://user-images.githubusercontent.com/31941670/222943799-b3653208-107a-4086-ad86-267ae244e56f.png">

**Comment by liangzh-404** [comment]
currently I am using below css snippet to fix:

div.tagfolder-quantity.itemscount.svelte-etffjf > span{
	color:var(--nav-item-color)!important;
}
div.taglist.svelte-etffjf > span{
	color:var(--nav-item-color)!important;
}

**Comment by vrtmrz** [comment]
Thank you for opening the issue! I missed it!
I will check and fix this in the next version.

**Comment by vrtmrz** [comment]
Sorry for being late!
This issue has been fixed at v0.15.21. Could you please try this version?

**Comment by liangzh-404** [comment]
yes, you fixed this !thanks~
