### ISSUE TITLE
Bug/FR: Opened note should become active pane - even if the previous note was pinned

### ISSUE THREAD

**Issue by avirosso** [vrtmrz/obsidian-tagfolder#7]
Problem: If my active note is a "pinned note" and I open another note from the TagFolder sidepane, the "pinned note" remains as active note. 

When I open a new note from TagFolder sidepane, it should always become the active pane (just like if I open a note from File Explorer).

**Comment by vrtmrz** [comment]
@avirosso I've forgotten to inform you this.
This issue should have been fixed in v0.6.2.
Could you please check it out?
