### ISSUE TITLE
提案: #_untaggedフォルダーのファイルをネスト0で表示する / Suggestion: #_untagged folder files in nested 0

### ISSUE THREAD

**Issue by yojiyama7** [vrtmrz/obsidian-tagfolder#70]
現在の仕様では、タグのついていないファイルは #_untagged フォルダに全て入っており"ネスト1の表示"がされています。
ただ、タグがついていないのなら"ネスト0の表示"の方法も直感的だと思います。

イラストを添えておきます。
何か確認不足がある発言をしていたらすみません。

---

(deepl translation)
Currently, untagged files are all in the #_untagged folder and are displayed as "nested 1".
However, if the files are untagged, I think the "nested 0" method is also intuitive.

Here is an illustration.
I apologize if I have said something that is not clear enough.

![obsidianTagFolderSuggestion](https://user-images.githubusercontent.com/17645288/236585235-14884be4-8740-4e25-985a-0d4251a1f16a.png)

**Comment by vrtmrz** [comment]
ありがとうございます！イラストを書いていただくとやっぱり凄くわかりやすいですね。
この挙動、単純に好みでこうした覚えがあります。
本来はいったん`_untagged`に入れたりせずに処理した方が良いかなと思うのですが、タイトルにいただいた通りの挙動の方が簡単だったので実装しました。
一度お試し下さい。

**Comment by Immortal-Sty** [comment]
Now the `#_untagged` folder still display. Could you add an option to hide it?

**Comment by vrtmrz** [comment]
Thank you for pointing this out!
I have implemented this, but now it seems broken. I will address it later!

**Comment by vrtmrz** [comment]
Thank you for your patience in my absence!  
I missed having an announcement, but it has been fixed at 0.18.5.
Would you please check the behaviour?

**Comment by Immortal-Sty** [comment]
It worked well, thanks.

**Comment by vrtmrz** [comment]
I am very glad to hear that! Thank you for your testing!
