### ISSUE TITLE
Why is the tag structure so deep and complex?

### ISSUE THREAD

**Issue by DeanIsMe** [vrtmrz/obsidian-tagfolder#72]
I don't understand why this plugin makes the tag structure so deep & complex. It appears to treat multiple tags like nested tags.
Below is the simple structure that I would expect, given your example notes.

```
Notes:
2021-11-01 : #daily/2021/11 #status/summarized
2021-11-02 : #daily/2021/11 #status/summarized
2021-11-03 : #daily/2021/11 #status/jot
2021-12-01 : #daily/2021/12 #status/jot

Tag structure:

daily
    → 2021
        → 11
            2021-11-01
            2021-11-02
            2021-11-03
        → 12
            2021-12-01

status
    → summarized
        2021-11-01
        2021-11-02
    → jot
        2021-11-03
        2021-12-01
```

Each tag results in 1 placement in the tag structure. 
I do not want to see every possible combination of different tags.

Is this possible, or am I missing something?

**Comment by vrtmrz** [comment]
Thank you for asking me! This is related to why I made this plug-in first.

Initially, this plug-in was created to find notes with some tags. This is to counter that some things are difficult to categorise in nature. I thought that even though not organised when storing them, We must be able to find them by simply following the recalled tags in order; If all relevant ones were shown.

Of course, thanks to you all your contributions, now this plugin is also useful for people who are able to organise things.

There are configurations which have a harsh name. Especially in initial items. (I had less experience in both using English and OSS). Please let me know about your idea! Now we can improve the features.

Could you please set the Limit to `Level 1`? Possibly leaks are there, but is it in the right direction?

**Comment by DeanIsMe** [comment]
Thank you for the super fast response!
I set the limit to Level 1 and it did not help. It caused some notes to disappear from where I'd expect them to be in TagFolder's view.

**Comment by DeanIsMe** [comment]
What I'm looking for, is exactly the same tag layout that's shown in the built-in 'Tags' pane, but also showing the pages underneath each tag.
![image](https://github.com/vrtmrz/obsidian-tagfolder/assets/4307776/9fbab2a2-83f8-48d1-ad28-6ddc12488215)

**Comment by vrtmrz** [comment]
Thank you for the reply!
I understood and, I realised that that feature has already been implemented after I started to write some patches for trial.

`Disable narrowing down` may work well for us. Could you please try the toggle once?

**Comment by DeanIsMe** [comment]
Disable narrowing down was exactly what I wanted! Thank you so much.
