### ISSUE TITLE
“Always Open” has disabled but still activate TagFolder at every obsidian launch

### ISSUE THREAD

**Issue by HopeLHP** [vrtmrz/obsidian-tagfolder#74]
![image](https://github.com/vrtmrz/obsidian-tagfolder/assets/70339118/2d548958-cf53-4904-ac73-7ec1e8495248)
<img width="1619" alt="image" src="https://github.com/vrtmrz/obsidian-tagfolder/assets/70339118/7d1717d8-9f1d-4603-9101-79d508f880ad">
os：macos13.4.1

**Comment by HopeLHP** [comment]
<img width="192" alt="image" src="https://github.com/vrtmrz/obsidian-tagfolder/assets/70339118/7886c281-1714-4b6a-9067-a7db922506cc">
why there is blank area

**Comment by vrtmrz** [comment]
Thank you for opening the issue!
I have not checked the source code yet, but the behaviour that you mentioned has been reproduced! I will investigate it!

The extra tags will be shown in the blank area.
(`Extra tags` means the tags which have not been used to build the hierarchy. If the note was tagged with "#A", "#B" and "#C", and then if we are opening "#A/#B", "#C" should be shown).

**Comment by vrtmrz** [comment]
Sorry for being late to inform this!
This issue has been fixed at v0.15.27. Would you please check this version?

**Comment by HopeLHP** [comment]
Solved! Everything is ok now.
thanks for your plugin!
