### ISSUE TITLE
Search doesn't show certain tags

### ISSUE THREAD

**Issue by plax-00** [vrtmrz/obsidian-tagfolder#78]
When all notes that contain a tag use only that one tag, it doesn't show up when searched for. For example, if I have 5 notes and they all only contain one tag `tag1`, then `tag1` doesn't show up in the search. But if any one of them also contains `tag2`, then both `tag1` and `tag2` will show up when searched for.

**Comment by vrtmrz** [comment]
Thank you for opening this issue! I have not realised this.
It could be reproduced, and fixed at v0.16.9.
Could you please check the latest version?

**Comment by plax-00** [comment]
It works, thank you!
