### ISSUE TITLE
A tag cannot show in tag folder

### ISSUE THREAD

**Issue by HopeLHP** [vrtmrz/obsidian-tagfolder#80]
tag folder:
<img width="235" alt="image" src="https://github.com/vrtmrz/obsidian-tagfolder/assets/70339118/ea26dfbb-d21f-4f2f-a755-03824db867c7">

obsidian tag:
<img width="200" alt="image" src="https://github.com/vrtmrz/obsidian-tagfolder/assets/70339118/ee038d61-66db-426f-ad49-dcd294c9340e">

as we can see, the tag "Zotero" cannot show

**Comment by vrtmrz** [comment]
Thank you for opening the issue! It could be reproduced!
It was caused on every tag which was included themselves inside other tags. (Depending processing order)

Fixed at v0.16.10. May I ask you to check the behaviour?

**Comment by HopeLHP** [comment]
the tag shows after updated, but the name seems abnormal?
the document under the tag:
<img width="228" alt="image" src="https://github.com/vrtmrz/obsidian-tagfolder/assets/70339118/b4b42553-79bf-4484-b4b9-e11be0934cff">
the document:
<img width="957" alt="image" src="https://github.com/vrtmrz/obsidian-tagfolder/assets/70339118/027c335b-601b-4a56-8f24-3be3f0ae1421">

**Comment by vrtmrz** [comment]
Thank you for testing! It looks like caused by `Use title` and using `{{`, `}}` inside the frontmatter YAML.
For now, we can quote that as like `"{{title}}"`, to avoid this. However, we should think about how to handle it...

**Comment by HopeLHP** [comment]
OK, `{{title}}`is the reason!
Thank you for your help!
