### ISSUE TITLE
Restrict each page to only be shown once?

### ISSUE THREAD

**Issue by andy47** [vrtmrz/obsidian-tagfolder#9]
Thanks for a great plugin. Is there a way to show each page only once in the tree?

I have a hierarchy for keeping my weekly journal notes;

    Journal
        2021
            12-December
                2021-12-06
                2021-12-13
                2021-12-20
                2021-12-27
        2022
            01-January
                2022-01-03
                ...
            02-February
                ...

But at the moment with TagFolder turned on the '2021-12-06' (with the tag `#Journal/2021/12-December`) page shows up under `12-December`, `2021` and `Journal` in the tree. 

Is there a way to only show this page under `12-December` in the tree above?

**Comment by vrtmrz** [comment]
As like #3, implemented on v0.8.0. 
Could you please try v0.8.0?

**Comment by andy47** [comment]
Perfect, thanks. Works exactly as I'd like.
