### ISSUE TITLE
The tag after the title cannot be displayed completely

### ISSUE THREAD

**Issue by Rigthi** [vrtmrz/obsidian-tagfolder#91]
![image](https://github.com/vrtmrz/obsidian-tagfolder/assets/117029315/ced724a1-96cc-402d-b075-171dde6e1ecb)
![image](https://github.com/vrtmrz/obsidian-tagfolder/assets/117029315/b9bfb663-520d-4db6-a5eb-4be1868c6b01)

your plugin is so useful that i use it everyday for viewing my much files,
but one thing makes me a little uncomfortable is this place.
there is still much place for tags to show, but why it is cut as the picture shows
maybe you can fix it for a better viewing experience,then ill be so much thankful and so is the ones who likes this plugin

**Comment by vrtmrz** [comment]
Thank you for asking me! I am so honoured to hear that you find my plugin so useful. It is always rewarding to know that my work is helping you all in your everyday lives.
As you mentioned, extra tags had a fixed maximum size and it is difficult to see. I was aware of it, but I had no inspiration about how to implement it, and I left it.

After seeing this issue, I sat down and thought about it again and found out successfully. I am so grateful for the contribution.

This feature has been implemented in 0.18.3! 
Would you mind if I ask you to check the behaviour, please?

**Comment by Rigthi** [comment]
i upadated my plugin and find your update has been applied perfectly .it realy helps me to view my tags of files better ,thank you!
