### ISSUE TITLE
[bug] When launch Obsidian, the tags page does not display any tags.

### ISSUE THREAD

**Issue by zhigang-he** [vrtmrz/obsidian-tagfolder#94]
Thank you for developing this plugin, it has been very helpful to me. However, I recently encountered an issue: every time I reopen Obsidian, the tag page in the sidebar is blank. I have set some filtering criteria in the settings page's "target folders" and "ignore note tag", and the tags reappear and fully comply with the filtering criteria whenever I change any of these settings. But even if I leave all the filters blank and reopen Obsidian, the tag page still shows no tags until I change the filter conditions. Could you suggest what might be causing this and how to resolve it?

**Comment by vrtmrz** [comment]
Thank you for your report! And, sorry for being late! I have finally reproduced it! 
If you are troubled as same as my reproduction, you may be using the LinkFolder too. 
This is a bug, but while using LinkFolder, some updates seem to be ignored in TagFolder.
I will address it soon!

**Comment by vrtmrz** [comment]
I found that the update checks of each tree were mixed up. 
It has been fixed at v0.18.4, would you please check the behaviour?

**Comment by zhigang-he** [comment]
I update the Tagfolder and delighted to find that this update perfectly solved my issue. Now everything is working as expected. Thank you very much!
